<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <LangVersion>latest</LangVersion>
    <RootNamespace>EQLogParser</RootNamespace>
    <AssemblyName>EQLogParser.Core</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="LiteDB" Version="5.0.17" />
    <PackageReference Include="Riok.Mapperly" Version="4.3.1" />
    <PackageReference Include="log4net" Version="3.3.1" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../EQLogParser.Utils/EQLogParser.Utils.csproj" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="EQLogParser" />
    <InternalsVisibleTo Include="EQLogParser.Test" />
    <InternalsVisibleTo Include="EQLogParser.Wpf.Test" />
  </ItemGroup>
  <PropertyGroup>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>
</Project>
