//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EQLogParser.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EQLogParser.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Berserker.
        /// </summary>
        internal static string BER {
            get {
                return ResourceManager.GetString("BER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bard.
        /// </summary>
        internal static string BRD {
            get {
                return ResourceManager.GetString("BRD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beastlord.
        /// </summary>
        internal static string BST {
            get {
                return ResourceManager.GetString("BST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Date.
        /// </summary>
        internal static string CHAT_END_DATE {
            get {
                return ResourceManager.GetString("CHAT_END_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        internal static string CHAT_FROM_FILTER {
            get {
                return ResourceManager.GetString("CHAT_FROM_FILTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date.
        /// </summary>
        internal static string CHAT_START_DATE {
            get {
                return ResourceManager.GetString("CHAT_START_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message Search.
        /// </summary>
        internal static string CHAT_TEXT_FILTER {
            get {
                return ResourceManager.GetString("CHAT_TEXT_FILTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To.
        /// </summary>
        internal static string CHAT_TO_FILTER {
            get {
                return ResourceManager.GetString("CHAT_TO_FILTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cleric.
        /// </summary>
        internal static string CLR {
            get {
                return ResourceManager.GetString("CLR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Columns Selected.
        /// </summary>
        internal static string COLUMNS_SELECTED {
            get {
                return ResourceManager.GetString("COLUMNS_SELECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Parse Title.
        /// </summary>
        internal static string CUSTOM_PARSE_TITLE {
            get {
                return ResourceManager.GetString("CUSTOM_PARSE_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Druid.
        /// </summary>
        internal static string DRU {
            get {
                return ResourceManager.GetString("DRU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enchanter.
        /// </summary>
        internal static string ENC {
            get {
                return ResourceManager.GetString("ENC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actor | Target Filter.
        /// </summary>
        internal static string EVENT_FILTER_TEXT {
            get {
                return ResourceManager.GetString("EVENT_FILTER_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can Not Save Summary Data.
        /// </summary>
        internal static string FILEMENU_EXPORT_SUMMARY {
            get {
                return ResourceManager.GetString("FILEMENU_EXPORT_SUMMARY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Results Filter.
        /// </summary>
        internal static string LOG_FILTER_TEXT {
            get {
                return ResourceManager.GetString("LOG_FILTER_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Term.
        /// </summary>
        internal static string LOG_SEARCH_TEXT {
            get {
                return ResourceManager.GetString("LOG_SEARCH_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Magician.
        /// </summary>
        internal static string MAG {
            get {
                return ResourceManager.GetString("MAG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monk.
        /// </summary>
        internal static string MNK {
            get {
                return ResourceManager.GetString("MNK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Necromancer.
        /// </summary>
        internal static string NEC {
            get {
                return ResourceManager.GetString("NEC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FIght/NPC Search.
        /// </summary>
        internal static string NPC_SEARCH_TEXT {
            get {
                return ResourceManager.GetString("NPC_SEARCH_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paladin.
        /// </summary>
        internal static string PAL {
            get {
                return ResourceManager.GetString("PAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Table Columns Restored!.
        /// </summary>
        internal static string RESTORE_TABLE_COLUMNS {
            get {
                return ResourceManager.GetString("RESTORE_TABLE_COLUMNS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ranger.
        /// </summary>
        internal static string RNG {
            get {
                return ResourceManager.GetString("RNG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rogue.
        /// </summary>
        internal static string ROG {
            get {
                return ResourceManager.GetString("ROG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Players Selected.
        /// </summary>
        internal static string SHARE_DPS_SELECTED {
            get {
                return ResourceManager.GetString("SHARE_DPS_SELECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exceeded Copy/Paste Limit for EQ.
        /// </summary>
        internal static string SHARE_DPS_TOO_BIG {
            get {
                return ResourceManager.GetString("SHARE_DPS_TOO_BIG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shadow Knight.
        /// </summary>
        internal static string SHD {
            get {
                return ResourceManager.GetString("SHD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shaman.
        /// </summary>
        internal static string SHM {
            get {
                return ResourceManager.GetString("SHM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warrior.
        /// </summary>
        internal static string WAR {
            get {
                return ResourceManager.GetString("WAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wizard.
        /// </summary>
        internal static string WIZ {
            get {
                return ResourceManager.GetString("WIZ", resourceCulture);
            }
        }
    }
}
