//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EQLogParser {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EQLogParser.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Classes.
        /// </summary>
        public static string ANY_CLASS {
            get {
                return ResourceManager.GetString("ANY_CLASS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Settings.
        /// </summary>
        public static string APP_SETTINGS {
            get {
                return ResourceManager.GetString("APP_SETTINGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Overlays.
        /// </summary>
        public static string ASSIGN_OVERLAY {
            get {
                return ResourceManager.GetString("ASSIGN_OVERLAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Priority on Selected Triggers.
        /// </summary>
        public static string ASSIGN_PRIORITY {
            get {
                return ResourceManager.GetString("ASSIGN_PRIORITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio Playback Failed.
        /// </summary>
        public static string AUDIO_ERROR {
            get {
                return ResourceManager.GetString("AUDIO_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Berserker.
        /// </summary>
        public static string BER {
            get {
                return ResourceManager.GetString("BER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #A00020.
        /// </summary>
        public static string BER_COLOR {
            get {
                return ResourceManager.GetString("BER_COLOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bard.
        /// </summary>
        public static string BRD {
            get {
                return ResourceManager.GetString("BRD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #C080C0.
        /// </summary>
        public static string BRD_COLOR {
            get {
                return ResourceManager.GetString("BRD_COLOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beastlord.
        /// </summary>
        public static string BST {
            get {
                return ResourceManager.GetString("BST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #D0B040.
        /// </summary>
        public static string BST_COLOR {
            get {
                return ResourceManager.GetString("BST_COLOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channels.
        /// </summary>
        public static string CHANNELS_SELECTED {
            get {
                return ResourceManager.GetString("CHANNELS_SELECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        public static string CHAT_FROM_FILTER {
            get {
                return ResourceManager.GetString("CHAT_FROM_FILTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message Search.
        /// </summary>
        public static string CHAT_TEXT_FILTER {
            get {
                return ResourceManager.GetString("CHAT_TEXT_FILTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To.
        /// </summary>
        public static string CHAT_TO_FILTER {
            get {
                return ResourceManager.GetString("CHAT_TO_FILTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking For Updates.
        /// </summary>
        public static string CHECK_VERSION {
            get {
                return ResourceManager.GetString("CHECK_VERSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classes.
        /// </summary>
        public static string CLASSES_SELECTED {
            get {
                return ResourceManager.GetString("CLASSES_SELECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Chat Archive.
        /// </summary>
        public static string CLEAR_CHAT {
            get {
                return ResourceManager.GetString("CLEAR_CHAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cleric.
        /// </summary>
        public static string CLR {
            get {
                return ResourceManager.GetString("CLR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #80C0FF.
        /// </summary>
        public static string CLR_COLOR {
            get {
                return ResourceManager.GetString("CLR_COLOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Columns.
        /// </summary>
        public static string COLUMNS_SELECTED {
            get {
                return ResourceManager.GetString("COLUMNS_SELECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy Large Image.
        /// </summary>
        public static string COPY_LARGE_IMAGE {
            get {
                return ResourceManager.GetString("COPY_LARGE_IMAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Backup File.
        /// </summary>
        public static string CREATE_BACKUP {
            get {
                return ResourceManager.GetString("CREATE_BACKUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Parse Title.
        /// </summary>
        public static string CUSTOM_PARSE_TITLE {
            get {
                return ResourceManager.GetString("CUSTOM_PARSE_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Druid.
        /// </summary>
        public static string DRU {
            get {
                return ResourceManager.GetString("DRU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #A0A040.
        /// </summary>
        public static string DRU_COLOR {
            get {
                return ResourceManager.GetString("DRU_COLOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enchanter.
        /// </summary>
        public static string ENC {
            get {
                return ResourceManager.GetString("ENC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #C0A0E0.
        /// </summary>
        public static string ENC_COLOR {
            get {
                return ResourceManager.GetString("ENC_COLOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actor | Target Filter.
        /// </summary>
        public static string EVENT_FILTER_TEXT {
            get {
                return ResourceManager.GetString("EVENT_FILTER_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event Types.
        /// </summary>
        public static string EVENT_TYPES_SELECTED {
            get {
                return ResourceManager.GetString("EVENT_TYPES_SELECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Failed.
        /// </summary>
        public static string EXPORT_ERROR {
            get {
                return ResourceManager.GetString("EXPORT_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can Not Save Summary Data.
        /// </summary>
        public static string FILEMENU_EXPORT_SUMMARY {
            get {
                return ResourceManager.GetString("FILEMENU_EXPORT_SUMMARY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Log File.
        /// </summary>
        public static string FILEMENU_OPEN_LOG {
            get {
                return ResourceManager.GetString("FILEMENU_OPEN_LOG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Selected Fights.
        /// </summary>
        public static string FILEMENU_SAVE_FIGHTS {
            get {
                return ResourceManager.GetString("FILEMENU_SAVE_FIGHTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder Delete.
        /// </summary>
        public static string FOLDER_DELETE {
            get {
                return ResourceManager.GetString("FOLDER_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Failed.
        /// </summary>
        public static string IMPORT_ERROR {
            get {
                return ResourceManager.GetString("IMPORT_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Types.
        /// </summary>
        public static string LINE_TYPES_SELECTED {
            get {
                return ResourceManager.GetString("LINE_TYPES_SELECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lines (Filtered).
        /// </summary>
        public static string LINES_FILTERED {
            get {
                return ResourceManager.GetString("LINES_FILTERED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Results Filter.
        /// </summary>
        public static string LOG_FILTER_TEXT {
            get {
                return ResourceManager.GetString("LOG_FILTER_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Term or Regex.
        /// </summary>
        public static string LOG_SEARCH_TEXT {
            get {
                return ResourceManager.GetString("LOG_SEARCH_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Magician.
        /// </summary>
        public static string MAG {
            get {
                return ResourceManager.GetString("MAG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #FFC040.
        /// </summary>
        public static string MAG_COLOR {
            get {
                return ResourceManager.GetString("MAG_COLOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monk.
        /// </summary>
        public static string MNK {
            get {
                return ResourceManager.GetString("MNK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #FFA040.
        /// </summary>
        public static string MNK_COLOR {
            get {
                return ResourceManager.GetString("MNK_COLOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Necromancer.
        /// </summary>
        public static string NEC {
            get {
                return ResourceManager.GetString("NEC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #404040.
        /// </summary>
        public static string NEC_COLOR {
            get {
                return ResourceManager.GetString("NEC_COLOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fight Search.
        /// </summary>
        public static string NPC_SEARCH_TEXT {
            get {
                return ResourceManager.GetString("NPC_SEARCH_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paladin.
        /// </summary>
        public static string PAL {
            get {
                return ResourceManager.GetString("PAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #dbb35c.
        /// </summary>
        public static string PAL_COLOR {
            get {
                return ResourceManager.GetString("PAL_COLOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received GINA Triggers.
        /// </summary>
        public static string RECEIVED_GINA {
            get {
                return ResourceManager.GetString("RECEIVED_GINA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received Quick Share.
        /// </summary>
        public static string RECEIVED_SHARE {
            get {
                return ResourceManager.GetString("RECEIVED_SHARE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Window State.
        /// </summary>
        public static string RESET_WINDOW_STATE {
            get {
                return ResourceManager.GetString("RESET_WINDOW_STATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart Required.
        /// </summary>
        public static string RESTART_NEEDED {
            get {
                return ResourceManager.GetString("RESTART_NEEDED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore From Backup.
        /// </summary>
        public static string RESTORE_FROM_BACKUP {
            get {
                return ResourceManager.GetString("RESTORE_FROM_BACKUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Table Columns Restored!.
        /// </summary>
        public static string RESTORE_TABLE_COLUMNS {
            get {
                return ResourceManager.GetString("RESTORE_TABLE_COLUMNS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ranger.
        /// </summary>
        public static string RNG {
            get {
                return ResourceManager.GetString("RNG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #40A040.
        /// </summary>
        public static string RNG_COLOR {
            get {
                return ResourceManager.GetString("RNG_COLOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rogue.
        /// </summary>
        public static string ROG {
            get {
                return ResourceManager.GetString("ROG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #fd4c46.
        /// </summary>
        public static string ROG_COLOR {
            get {
                return ResourceManager.GetString("ROG_COLOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select All.
        /// </summary>
        public static string SELECT_ALL {
            get {
                return ResourceManager.GetString("SELECT_ALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Players Selected.
        /// </summary>
        public static string SHARE_DPS_SELECTED {
            get {
                return ResourceManager.GetString("SHARE_DPS_SELECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exceeded Copy/Paste Limit for EQ.
        /// </summary>
        public static string SHARE_DPS_TOO_BIG {
            get {
                return ResourceManager.GetString("SHARE_DPS_TOO_BIG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quick Share Failed.
        /// </summary>
        public static string SHARE_ERROR {
            get {
                return ResourceManager.GetString("SHARE_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quick Share.
        /// </summary>
        public static string SHARE_MESSAGE {
            get {
                return ResourceManager.GetString("SHARE_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shadow Knight.
        /// </summary>
        public static string SHD {
            get {
                return ResourceManager.GetString("SHD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #604080.
        /// </summary>
        public static string SHD_COLOR {
            get {
                return ResourceManager.GetString("SHD_COLOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shaman.
        /// </summary>
        public static string SHM {
            get {
                return ResourceManager.GetString("SHM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #40C0C0.
        /// </summary>
        public static string SHM_COLOR {
            get {
                return ResourceManager.GetString("SHM_COLOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spell Types.
        /// </summary>
        public static string SPELL_TYPES_SELECTED {
            get {
                return ResourceManager.GetString("SPELL_TYPES_SELECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Character Settings.
        /// </summary>
        public static string TRIGGER_CHARACTER_DELETE {
            get {
                return ResourceManager.GetString("TRIGGER_CHARACTER_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trigger Search.
        /// </summary>
        public static string TRIGGER_SEARCH_TEXT {
            get {
                return ResourceManager.GetString("TRIGGER_SEARCH_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Overlays.
        /// </summary>
        public static string UNASSIGN_OVERLAY {
            get {
                return ResourceManager.GetString("UNASSIGN_OVERLAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsaved Changes.
        /// </summary>
        public static string UNSAVED {
            get {
                return ResourceManager.GetString("UNSAVED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unselect All.
        /// </summary>
        public static string UNSELECT_ALL {
            get {
                return ResourceManager.GetString("UNSELECT_ALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warrior.
        /// </summary>
        public static string WAR {
            get {
                return ResourceManager.GetString("WAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #C04040.
        /// </summary>
        public static string WAR_COLOR {
            get {
                return ResourceManager.GetString("WAR_COLOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wizard.
        /// </summary>
        public static string WIZ {
            get {
                return ResourceManager.GetString("WIZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #4080C0.
        /// </summary>
        public static string WIZ_COLOR {
            get {
                return ResourceManager.GetString("WIZ_COLOR", resourceCulture);
            }
        }
    }
}
